dx/force-app/main/default/objects/ltng_CompValidationBase__c/ltng_CompValidationBase__c.object-meta.xml
<CustomObject>
    <description>Object to test validation with</description>
    <label>Comp Validation Base</label>
    <nameField>
        <label>Comp Validation Base Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comp Validation Bases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dx/force-app/main/default/objects/ltng_CompValidationBase__c/fields/Level1__c.field-meta.xml
<CustomField>
    <fullName>Level1__c</fullName>
    <label>Level 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dx/force-app/main/default/objects/ltng_CompValidationBase__c/fields/Level2__c.field-meta.xml
<CustomField>
    <fullName>Level2__c</fullName>
    <label>Level 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dx/force-app/main/default/objects/ltng_CompValidationBase__c/fields/Level3__c.field-meta.xml
<CustomField>
    <fullName>Level3__c</fullName>
    <label>Level 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dx/force-app/main/default/objects/ltng_CompValidationBase__c/fields/Level4__c.field-meta.xml
<CustomField>
    <fullName>Level4__c</fullName>
    <label>Level 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dx/force-app/main/default/objects/ltng_CompValidationBase__c/fields/Level5__c.field-meta.xml
<CustomField>
    <fullName>Level5__c</fullName>
    <label>Level 5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

dx/force-app/main/default/objects/ltng_CompValidationBase__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In-progress</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

dx/force-app/main/default/classes/ltng_InputFieldValidationController.cls
public with sharing class ltng_InputFieldValidationController
{
	@AuraEnabled
    public static List<ltng_InputFieldValidationData> getInputFieldValidationData()
    {
        // Perform isAccessible() check here
		
        // ltng_InputFieldValidationData is a simple "wrapper" Apex class for transport
        List<ltng_InputFieldValidationData> returnValue = new List<ltng_InputFieldValidationData>();
        List<ltng_CompValidationBase__c> items = [SELECT Id, Name, Status__c, Level1__c, Level2__c, Level3__c, Level4__c, Level5__c FROM ltng_CompValidationBase__c LIMIT 5];
        
        for (ltng_CompValidationBase__c item : items)
        {
            returnValue.add(new ltng_InputFieldValidationData(item.Id, item.Name, item.Status__c, item.Level1__c, item.Level2__c, item.Level3__c, item.Level4__c, item.Level5__c));
        }
        
        return returnValue;
    }
}